# -*- coding: utf-8 -*-
"""tugas_akhir_psd_judul_3_2515061104_psti_b_dap_rafi_aji_c_u.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yU-FgntfoA-UzYMrMkoHRKLHv_xLRiHc
"""

def binary_search(arr, n, target):
    l = 0
    r = n - 1
    pos = -1
    while l <= r:
        m = l + (r - l) // 2
        print(f"Median: {m}, nilai: {arr[m]}")
        if arr[m] == target:
            pos = m
            break
        elif arr[m] < target:
            print("Mencari di kanan")
            l = m + 1
        else:
            print("Mencari di kiri")
            r = m - 1
    return pos


def main():
    n = 7
    arr = ["Agung", "Aji",  "Cahyo", "Dimas", "Prabowo", "Rafi", "Utomo"]
    print(f"Array: {arr}")
    while True:
        try:
            x = str(input("Masukkan nama yang ingin dicari: "))
            target = x.title()
            break
        except ValueError:
            print("Input tidak valid, silakan masukkan kata(Tanpa angka dan karakter unik)!")
    pos = binary_search(arr, n, target)
    if pos != -1:
        print(f"Ditemukan pada nomor ke-{pos + 1}")
    else:
        print("Tidak ditemukan")


if __name__ == "__main__":
    main()