# -*- coding: utf-8 -*-
"""Tugas akhir PSD Judul 2_PSTI B_2515061104_DAP. Rafi Aji C. U.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139Jp_-MpdbWuBr1rGViT1KSb4euzmXJB
"""

def tukar(arr, i, j):
    temp = arr[i]
    arr[i] = arr[j]
    arr[j] = temp


def bubble_sort(arr, n):
    for i in range(n - 1):
        for j in range(n - i - 1):
            if arr[j] > arr[j + 1]:
                tukar(arr, j, j + 1)


def main():
    try:
        n = int(input("Masukkan jumlah file yang ada: "))
    except ValueError:
        print("Input tidak valid!")
        return
    arr = []
    print("Masukkan besar fila (Dalam satuan KiloByte):")
    for i in range(n):
        while True:
            try:
                nilai = int(input())
                arr.append(nilai)
                break
            except ValueError:
                print("Input tidak valid, silakan masukkan angka!")
    print(f"File sebelum diurutkan: {arr}")
    bubble_sort(arr, n)
    print("File setelah diurutkan :", end=" ")
    for i in range(n):
        print(arr[i], end=" ")
    print()


if __name__ == "__main__":
    main()