# -*- coding: utf-8 -*-
"""TA PSD judul 4_DAP. Rafi Aji C. U_2515061104.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-S4YHShiW7tnjrCGUa9crqEP1wWzZKOY
"""

class QueueArray:
    def __init__(self, max_size=100):
        self.MAXN = max_size
        self.q = [None] * self.MAXN
        self.front_idx = -1
        self.rear_idx = -1

    def is_empty(self):
        return self.front_idx == -1

    def is_full(self):
        return (self.rear_idx + 1) % self.MAXN == self.front_idx

    def enqueue(self, x):
        if self.is_full():
            print("Antrean penuh")
            return
        if self.is_empty():
            self.front_idx = 0
            self.rear_idx = 0
        else:
            self.rear_idx = (self.rear_idx + 1) % self.MAXN
        self.q[self.rear_idx] = x
        print(
    f"Pasien dengan nama {x} berhasil ditambahkan ke antrean. "
    f"Estimasi waktu tunggu adalah {(self.rear_idx - self.front_idx) * 5} menit. "
    f"(Karena ada {self.rear_idx - self.front_idx} orang di depan)"
     )
    def dequeue(self):
        if self.is_empty():
            print("Antrean Pasien kosong")
            return
        print(f"Nomor antrean {self.q[self.front_idx]} silahkan menuju loket obat")
        if self.front_idx == self.rear_idx:
            self.front_idx = -1
            self.rear_idx = -1
        else:
            self.front_idx = (self.front_idx + 1) % self.MAXN

    def peek(self):
        if self.is_empty():
            print("Antrian pasien kosong")
            return
        print(f"Pasien obat paling depan adalah: {self.q[self.front_idx]}")

    def display(self):
        if self.is_empty():
            print("Queue kosong")
            return
        print("Isi Antrean (depan ke belakang): ", end="")
        i = self.front_idx
        while True:
            print(self.q[i], end=" ")
            if i == self.rear_idx:
                break
            i = (i + 1) % self.MAXN
        print()


def main():
    queue = QueueArray()
    pilih = 0
    while pilih != 5:
        print("\n=== Sistem antrean Pasien klinik Unila ===")
        print("1. Tambah Pasien (Enqueue)")
        print("2. Layani Pasien (Dequeue)")
        print("3. Lihat pasien paling depan (peek)")
        print("4. Tampilkan")
        print("5. Keluar")
        try:
            pilih = int(input("Pilih: "))
        except ValueError:
            print("Input tidak valid!")
            continue
        if pilih == 1:
            try:
                val = str(input("Antrean Pasien : "))
                queue.enqueue(val)
            except ValueError:
                print("Input tidak valid!")

        elif pilih == 2:
            queue.dequeue()
        elif pilih == 3:
            queue.peek()
        elif pilih == 4:
            queue.display()
        elif pilih == 5:
            print("Program selesai.")
        else:
            print("Pilihan tidak valid!")


if __name__ == "__main__":
    main()