# -*- coding: utf-8 -*-
"""Tugas Akhir PSD judul 1_2515061104_PSTI B_DAP. Rafi Aji C. U.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YwFgTOMFpgnlDinMpoF6BsWKGYhq3HK
"""

#Sistem antrian gacoan

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self):
        self.start = None
        self.rear = None

    def create_new_node(self, n):
        new_node = Node(n)
        return new_node

    def insert_at_beg(self, new_node):
        if self.start is None:
            self.start = new_node
            self.rear = new_node
        else:
            new_node.next = self.start
            self.start = new_node

    def insert_at_end(self, new_node):
        if self.start is None:
            self.start = new_node
            self.rear = new_node
        else:
            self.rear.next = new_node
            self.rear = new_node

    def delete_node(self):
        if self.start is None:
            print("Underflow!!!")
        else:
            deleted_data = self.start.data
            self.start = self.start.next
            print(f"Node dengan data {deleted_data} telah dihapus.")
            if self.start is None:
                self.rear = None

    def display(self):
        if self.start is None:
            print("(kosong)")
            return
        current = self.start
        while current is not None:
            print(current.data, end=" -> ")
            current = current.next
        print("None")

def main():
    ll = LinkedList()
    print("Antrian Gacoan ")

    while True:
        print("1. Tambah antrian baru")
        print("2. Hapus antrian pertama (layani)")
        print("3. Tampilkan antrian")
        print("4. Keluar")

        choice = input("Pilih opsi (1/2/3/4): ")

        if choice == '1':
            nama = input("Masukkan nama orang yang ingin antri: ")
            new_node = ll.create_new_node(nama)
            if new_node:
                ll.insert_at_end(new_node)
                print(f"' {nama} ' berhasil ditambahkan ke antrian.")
            else:
                print("Gagal membuat node baru.")
        elif choice == '2':
            if ll.start is None:
                print("Antrian kosong, tidak ada yang bisa dilayani.")
            else:
                ll.delete_node()
        elif choice == '3':
            print("Antrian saat ini: ", end="")
            ll.display()
        elif choice == '4':
            print("Program selesai.")
            break
        else:
            print("Pilihan tidak valid, coba lagi.")

        if choice != '3' and choice != '4':
            print("Antrian saat ini: ", end="")
            ll.display()

if __name__ == "__main__":
    main()

