# -*- coding: utf-8 -*-
"""TA PSD Judul 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aJmtgm-8NjVOWmgB25IC8LIIV4tTMTnD
"""

class Node:
    def __init__(self, key, value):
        self.key = key
        self.value = value
        self.next = None


class HashMapSeparateChaining:
    def __init__(self, size=10):
        self.SIZE = size
        self.table = [None] * self.SIZE

    def hash_function(self, key):
        return (key % self.SIZE + self.SIZE) % self.SIZE

    def insert(self, key, value):
        index = self.hash_function(key)
        current = self.table[index]
        while current is not None:
            if current.key == key:
                current.value = value
                return
            current = current.next
        new_node = Node(key, value)
        new_node.next = self.table[index]
        self.table[index] = new_node

    def search(self, key):
        index = self.hash_function(key)
        current = self.table[index]
        while current is not None:
            if current.key == key:
                return current
            current = current.next
        return None

    def remove_key(self, key):
        index = self.hash_function(key)
        current = self.table[index]
        prev = None
        while current is not None:
            if current.key == key:
                if prev is None:
                    self.table[index] = current.next
                else:
                    prev.next = current.next
                return True
            prev = current
            current = current.next
        return False

    def display(self):
        print("\nDaftar Data Buku Perpustakaan:")
        for i in range(self.SIZE):
            print(f"{i}: ", end="")
            current = self.table[i]
            while current is not None:
                print(f"({current.key},{current.value}) -> ", end="")
                current = current.next
            print("Kosong")


def main():
    hashmap = HashMapSeparateChaining()
    hashmap.insert(10, "Buku Kalkulus")
    hashmap.insert(11, "Buku Matdis")
    hashmap.insert(25, "Buku Aljabar")
    hashmap.insert(21, "Buku Trigonometri")
    hashmap.insert(61, "Buku Dongeng")
    hashmap.insert(66, "Buku Cerita Nabi")
    hashmap.insert(15, "Buku Atomic Habits")
    hashmap.display()
    pilih = 0
    while pilih != 5:
        print("\nSistem Data Buku Perpustakaan")
        print("1. Tambah Buku")
        print("2. Cari Buku")
        print("3. Hapus Buku")
        print("4. Tampilkan")
        print("5. Keluar")
        try:
            pilih = int(input("Pilih: "))
        except ValueError:
            print("Input tidak valid!")
            continue
        if pilih == 1:
            try:
                npm = input("Masukan Kode Buku Baru: ")
                nama = input("Masukan Nama Buku Baru: ")
                hashmap.insert(int(npm), nama)
                print("\nDaftar Buku setelah ditambah:")
            except ValueError:
                print("Input tidak valid!")
        elif pilih == 2:
            cari = int(input("\nMasukan Kode buku yang ingin dicari: "))
            hasil = hashmap.search(cari)
            if hasil is not None:
                print(f"\nKode Buku {cari} ditemukan dengan nama {hasil.value}")
            else:
                print("\n Buku tidak ditemukan")
        elif pilih == 3:
            try:
                x = int(input("\nMasukan Kode Buku yang ingin dihapus: "))
                if hashmap.search(x) is not None:
                    hashmap.remove_key(x)
                    print(f"\nKode Buku {x} dengan nama {hasil.value} telah dihapus.")
                else:
                    print(f"\nKode Buku {x} tidak ada dalam daftar!")
            except ValueError:
                print("Kode tidak valid!")

        elif pilih == 4:
            hashmap.display()
        elif pilih == 5:
            print("Program selesai.")
        else:
            print("Pilihan tidak valid!")

if __name__ == "__main__":
    main()