# -*- coding: utf-8 -*-
"""TA PSD JUDUL 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2D58L_8NIglTHcAiRfiDlmUx2lnwSV8
"""

class Node:
    def __init__(self, key):
        self.key = key
        self.left = None
        self.right = None


class BSTLanjut:
    def __init__(self):
        self.root = None

    def insert_node(self, root, key):
        if root is None:
            print(f"Ruangan {key} berhasil dimasukkan dan dapat digunakan")
            return Node(key)
        if key < root.key:
            root.left = self.insert_node(root.left, key)
        elif key > root.key:
            root.right = self.insert_node(root.right, key)
        else:
            print(f"Ruangan {key} sedang terpakai, Cari ruangan lain")
        return root

    def insert(self, key):
        if 1 <= key <= 20:
            self.root = self.insert_node(self.root, key)
        else:
            print("Nomor ruangan tidak valid, hanya ada ruangan dengan nomor 1-20")

    def find_min_node(self, root):
        current = root
        while current is not None and current.left is not None:
            current = current.left
        return current

    def delete_node(self, root, key):
        if root is None:
            return None
        if key < root.key:
            root.left = self.delete_node(root.left, key)
        elif key > root.key:
            root.right = self.delete_node(root.right, key)
        else:
            if root.left is None and root.right is None:
                return None
            elif root.left is None:
                return root.right
            elif root.right is None:
                return root.left
            else:
                successor = self.find_min_node(root.right)
                root.key = successor.key
                root.right = self.delete_node(root.right, successor.key)
        return root

    def delete(self, key):
        self.root = self.delete_node(self.root, key)

    def find_successor(self, root, key):
        current = root
        successor = None
        while current is not None:
            if key < current.key:
                successor = current
                current = current.left
            elif key > current.key:
                current = current.right
            else:
                break
        if current is None:
            return None, False
        if current.right is not None:
            successor = self.find_min_node(current.right)
        if successor is None:
            return None, False
        return successor.key, True

    def find_predecessor(self, root, key):
        current = root
        predecessor = None
        while current is not None:
            if key > current.key:
                predecessor = current
                current = current.right
            elif key < current.key:
                current = current.left
            else:
                break
        if current is None:
            return None, False
        if current.left is not None:
            temp = current.left
            while temp.right is not None:
                temp = temp.right
            predecessor = temp
        if predecessor is None:
            return None, False
        return predecessor.key, True

    def inorder(self, root):
        if root is None:
            return
        self.inorder(root.left)
        print(root.key, end=" ")
        self.inorder(root.right)

def main():
    bst = BSTLanjut()
    pilih = 0
    while pilih != 6:
        print("\n=== BST (Lanjutan) ===")
        print("1. Memasukan kelas yang akan digunakan")
        print("2. Menghapus kelas yang tidak digunakan")
        print("3. Menampilkan kelas yang digunakan")
        print("4. Menampilkan nomor ruangan terdekat yang lebih besar dari nomor yang dicek.")
        print("5. Menampilkan nomor ruangan terdekat yang lebih kecil dari nomor yang dicek.")
        print("6. Keluar program")
        try:
            pilih = int(input("Pilih: "))
        except ValueError:
            print("Input tidak valid!")
            continue
        if pilih == 1:
            try:
                x = int(input("Masukkan nomor ruangan kelas yang ingin digunakan: "))
                bst.insert(x)
            except ValueError:
                print("Input ruangan tidak valid!")
        elif pilih == 2:
            try:
                x = int(input("Hapus nomor ruangan (telah selesai digunakan): "))
                bst.delete(x)
                print(f"Nomor ruangan {x} telah selesai digunakan")
                print("Nomor Kelas yang masih terpakai: ", end="")
                bst.inorder(bst.root)
                print()
            except ValueError:
                print("Input tidak valid!")

        elif pilih == 3:
            print("Nomor kelas yang masih terpakai: ", end="")
            bst.inorder(bst.root)
            print()
        elif pilih == 4:
            try:
                x = int(input("Cari Ruangan terdekat yang dibagian kanan (lebih besar): "))
                ans, found = bst.find_successor(bst.root, x)
                if found:
                    print(f"Ruangan yang dicari adalah: {ans}")
                else:
                    print("Tidak ada Ruangan yang ditemukan (mungkin ruangan tidak ada atau yang terbesar)")
            except ValueError:
                print("Input tidak valid!")
        elif pilih == 5:
            try:
                x = int(input("Cari Ruangan yang terdekat di bagian kiri(lebih kecil): "))
                ans, found = bst.find_predecessor(bst.root, x)
                if found:
                    print(f"Ruangan yang dicari adalah: {ans}")
                else:
                    print("Tidak ada Ruangan yang ditemukan (mungkin ruangan tidak ada atau yang terkecil)")
            except ValueError:
                print("Input tidak valid!")
        elif pilih == 6:
            print("Program selesai.")
        else:
            print("Pilihan tidak valid!")


if __name__ == "__main__":
    main()